-- Floor Tile SaaS - Seed Products
-- Migration 002: Insert 38 SKUs

INSERT INTO products (sku, category, rotation) VALUES
-- MADERAS
('NOGAL CAFÉ', 'MADERAS', NULL),
('CEIBA GRIS OSC', 'MADERAS', NULL),
('CEIBA GRIS OSCURO BTE', 'MADERAS', NULL),
('CEIBA BEIGE', 'MADERAS', NULL),
('SAMAN BEIGE', 'MADERAS', NULL),
('CEIBA CAFÉ', 'MADERAS', NULL),
('NOGAL BEIGE', 'MADERAS', NULL),
('NOGAL GRIS OSC', 'MADERAS', NULL),
('ALMENDRO GRIS', 'MADERAS', NULL),
('ALMENDRO BEIGE', 'MADERAS', NULL),
('SAMAN GRIS', 'MADERAS', NULL),
('SAMAN CAFÉ', 'MADERAS', NULL),
('BARANOA GRIS', 'MADERAS', NULL),
('MOMPOX BEIGE', 'MADERAS', NULL),
('MOMPOX CAFÉ', 'MADERAS', NULL),
('ROBLE BEIGE', 'MADERAS', NULL),
('ROBLE GRIS', 'MADERAS', NULL),

-- EXTERIORES
('TOLU GRIS', 'EXTERIORES', NULL),
('QUIMBAYA BEIGE', 'EXTERIORES', NULL),
('TOLU BEIGE', 'EXTERIORES', NULL),
('QUIMBAYA GRIS', 'EXTERIORES', NULL),
('CIRCASIA', 'EXTERIORES', NULL),
('CALARCA', 'EXTERIORES', NULL),
('TOLU CAFE', 'EXTERIORES', NULL),
('GALERA RUSTICO GRIS', 'EXTERIORES', NULL),
('PIJAO', 'EXTERIORES', NULL),
('SALENTO GRIS', 'EXTERIORES', NULL),

-- MARMOLIZADOS
('MALAMBO GRIS', 'MARMOLIZADOS', NULL),
('CARACOLI', 'MARMOLIZADOS', NULL),
('MANAURE GRIS', 'MARMOLIZADOS', NULL),
('NECOCLI BEIGE', 'MARMOLIZADOS', NULL),
('MIRACLE', 'MARMOLIZADOS', NULL),
('NECOCLI GRIS', 'MARMOLIZADOS', NULL),
('MALAMBO BEIGE', 'MARMOLIZADOS', NULL),
('MANAURE BEIGE', 'MARMOLIZADOS', NULL),
('TERRA FUERTE', 'MARMOLIZADOS', NULL),
('MALAGA GRIS', 'MARMOLIZADOS', NULL),
('MALAGA BEIGE', 'MARMOLIZADOS', NULL);

-- Note: Rotation values (ALTA, MEDIA-ALTA, MEDIA, BAJA) to be filled by owner
-- System will also learn and suggest rotation based on sales velocity